### ISSUE TITLE
Use `Promise` instead of `jQuery.Deferred`

### ISSUE THREAD

**Issue by roobie** [eakron/sharepoint-utilities#3]
I think we should use the polyfillable `Promise` API instead of the more proprietary jQuery `Deferred` API. Until the Promise object is ubiquitous we can use e.g. Bluebird for developement purposes and suggest it to our users as a polyfill.

**Comment by eakron** [comment]
I want to avoid requiring our users to handle dependencies themselves, maybe we should do a dist file with eg Bluebird built in.

**Comment by roobie** [comment]
Yes, I concur. Let's bundle https://github.com/jakearchibald/es6-promise
